### ISSUE TITLE
目前已知bug

### ISSUE THREAD

**Issue by Mikoto-qiuhua** [Glom-c/FightSystem#1]
1.mm技能兼容   att-damage        内部实现最后是使用mm的api     doDamage来打伤害的 这个玩意必须得同步运行  不然在某些异步的技能内执行时会报错
2.玩家持续攻击时会无敌   看过实现的代码了  可能是因为错误的给攻击者添加了无敌帧         经过我测试   当我把无敌帧功能关闭后  玩家持续攻击也会正常受到伤害

**Comment by Glomzzz** [comment]
谢谢睡觉仙人，下版修

**Comment by Glomzzz** [comment]
修了，tks
